services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php
      - django
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./consult-drc-main:/var/www/consult-drc-main:ro
      - ./staticfiles:/srv/django/static:ro
      - ./media:/srv/django/media:ro
    environment:
      - TZ=Africa/Kigali
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./consult-drc-main:/var/www/consult-drc-main
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file: .env
    command: bash -lc "python manage.py collectstatic --noinput || true && gunicorn consult.wsgi:application -b 0.0.0.0:8000 --workers 3 --timeout 60"
    volumes:
      - ./:/app
    expose:
      - "8000"
    restart: unless-stopped

