# Generated by Django 5.2.5 on 2025-08-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('aeroport', models.CharField(max_length=120)),
                ('date_vol', models.DateField()),
                ('heure_vol', models.TimeField()),
                ('num_vol', models.CharField(blank=True, max_length=60)),
                ('langue', models.CharField(max_length=10)),
                ('infos', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aeroport', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ConciergerieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('urgence', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciergerie', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('hebergement', models.CharField(max_length=50)),
                ('chambre', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('infos', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='OtherServicesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autres', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='TDGRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(blank=True, default=list)),
                ('traduction_docs_autre', models.CharField(blank=True, max_length=150)),
                ('assistance_details', models.TextField(blank=True)),
                ('guide_langue', models.CharField(blank=True, max_length=10)),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tdg', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree', models.CharField(max_length=50)),
                ('duree_autre', models.CharField(blank=True, max_length=100)),
                ('vehicule', models.CharField(max_length=50)),
                ('finalite', models.CharField(max_length=100)),
                ('services', models.JSONField(blank=True, default=list)),
                ('lieu_depose', models.CharField(blank=True, max_length=150)),
                ('infos', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dashboard.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='VisaCarteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=80)),
                ('duree', models.CharField(blank=True, max_length=20)),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='dashboard.servicerequest')),
            ],
        ),
    ]
