# Generated by Django 5.2.5 on 2025-08-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_service_servicerequest_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='besoins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
