# Generated by Django 5.2.5 on 2025-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_hotelreservation_besoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportassistance',
            name='langue_autre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='airportassistance',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conciergerierequest',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='assistance_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='guide_accompagnement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='guide_lieux',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='guide_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='langue_cible',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='langue_source',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='legalisation',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='tdgrequest',
            name='traduction_docs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
