# Generated by Django 5.2.5 on 2025-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_airportassistance_langue_autre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visacarterequest',
            name='but_sejour',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visacarterequest',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='visacarterequest',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='visacarterequest',
            name='etab_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visacarterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='visacarterequest',
            name='nom',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='visacarterequest',
            name='pays',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='visacarterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visacarterequest',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
