# Generated by Django 5.2.1 on 2025-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_visacarterequest_but_sejour_visacarterequest_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
